name: Daily Tech Update
on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # This line below tells GitHub to use the newer Node version immediately
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24' # Changed from 20 to 24

      - name: Fetch Latest News
        run: node scraper.js

      - name: Save to Repo
        run: |
          git config --global user.name "NG-Tech-Bot"
          git config --global user.email "bot@ngtechhub.com"
          git add news.json
          git commit -m "Auto-update: $(date)" || exit 0
          git push
