name: NG-Tech-Auto-Deploy

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 0 * * *' # Updates daily
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Upload Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy
        uses: actions/deploy-pages@v4
